//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushVodIngestion.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/PushVodIngestion.ServiceProvider")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);
        
        string EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        PushVodIngestion.ServiceReference1.CompositeType GetDataUsingDataContract(PushVodIngestion.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.IAsyncResult BeginGetDataUsingDataContract(PushVodIngestion.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState);
        
        PushVodIngestion.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEntities", ReplyAction="http://tempuri.org/IService1/GetEntitiesResponse")]
        System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> GetEntities(string entityTypeName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetEntities", ReplyAction="http://tempuri.org/IService1/GetEntitiesResponse")]
        System.IAsyncResult BeginGetEntities(string entityTypeName, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> EndGetEntities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEntitiesBasedOnCondition", ReplyAction="http://tempuri.org/IService1/GetEntitiesBasedOnConditionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FrameWork.BusinessValidationResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FrameWork.EntityState))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tbl_Adi_ingest_item_file_info))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblAutomation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblPlayoutPort>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblPlayoutPort))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblPlaylist>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblPlaylist))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblChannel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblIngestion>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblIngestion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblDe))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblReportVersion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblSourceType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblSrc))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblChannel>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.vwApprovedPlaylist))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.vwChannel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.vwDubList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.vwIngestion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.ServiceReference1.CompositeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Framework.LINQEntityBase))]
        System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> GetEntitiesBasedOnCondition(string entityTypeName, string predicate, System.Collections.ObjectModel.ObservableCollection<object> value);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetEntitiesBasedOnCondition", ReplyAction="http://tempuri.org/IService1/GetEntitiesBasedOnConditionResponse")]
        System.IAsyncResult BeginGetEntitiesBasedOnCondition(string entityTypeName, string predicate, System.Collections.ObjectModel.ObservableCollection<object> value, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> EndGetEntitiesBasedOnCondition(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SavePlaylist", ReplyAction="http://tempuri.org/IService1/SavePlaylistResponse")]
        bool SavePlaylist(PushVodIngestion.DataProvider.tblPlaylist playList);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SavePlaylist", ReplyAction="http://tempuri.org/IService1/SavePlaylistResponse")]
        System.IAsyncResult BeginSavePlaylist(PushVodIngestion.DataProvider.tblPlaylist playList, System.AsyncCallback callback, object asyncState);
        
        bool EndSavePlaylist(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/data_command", ReplyAction="http://tempuri.org/IService1/data_commandResponse")]
        void data_command(string sqlCommand);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/data_command", ReplyAction="http://tempuri.org/IService1/data_commandResponse")]
        System.IAsyncResult Begindata_command(string sqlCommand, System.AsyncCallback callback, object asyncState);
        
        void Enddata_command(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserIngestion", ReplyAction="http://tempuri.org/IService1/GetUserIngestionResponse")]
        System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblIngestion> GetUserIngestion(long userSID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetUserIngestion", ReplyAction="http://tempuri.org/IService1/GetUserIngestionResponse")]
        System.IAsyncResult BeginGetUserIngestion(long userSID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblIngestion> EndGetUserIngestion(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserChannels", ReplyAction="http://tempuri.org/IService1/GetUserChannelsResponse")]
        System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblPlayoutPort> GetUserChannels(long userSID);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetUserChannels", ReplyAction="http://tempuri.org/IService1/GetUserChannelsResponse")]
        System.IAsyncResult BeginGetUserChannels(long userSID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblPlayoutPort> EndGetUserChannels(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Save", ReplyAction="http://tempuri.org/IService1/SaveResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tbl_Adi_ingest_item_file_info))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblAutomation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblPlayoutPort))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblPlaylist))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblChannel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblIngestion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblDe))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblReportVersion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblSourceType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.tblSrc))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.vwApprovedPlaylist))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.vwChannel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.vwDubList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.vwIngestion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PushVodIngestion.DataProvider.User))]
        Framework.LINQEntityBase Save(Framework.LINQEntityBase entity, FrameWork.EntityState entityState);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Save", ReplyAction="http://tempuri.org/IService1/SaveResponse")]
        System.IAsyncResult BeginSave(Framework.LINQEntityBase entity, FrameWork.EntityState entityState, System.AsyncCallback callback, object asyncState);
        
        Framework.LINQEntityBase EndSave(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/data_set", ReplyAction="http://tempuri.org/IService1/data_setResponse")]
        System.Data.DataTable data_set(string sqlCommand);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/data_set", ReplyAction="http://tempuri.org/IService1/data_setResponse")]
        System.IAsyncResult Begindata_set(string sqlCommand, System.AsyncCallback callback, object asyncState);
        
        System.Data.DataTable Enddata_set(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Bulk_Copy", ReplyAction="http://tempuri.org/IService1/Bulk_CopyResponse")]
        void Bulk_Copy(System.Data.DataTable dt, string destinationTable);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Bulk_Copy", ReplyAction="http://tempuri.org/IService1/Bulk_CopyResponse")]
        System.IAsyncResult BeginBulk_Copy(System.Data.DataTable dt, string destinationTable, System.AsyncCallback callback, object asyncState);
        
        void EndBulk_Copy(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PushVodIngestion.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PushVodIngestion.ServiceReference1.CompositeType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PushVodIngestion.ServiceReference1.CompositeType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEntitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEntitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEntitiesBasedOnConditionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEntitiesBasedOnConditionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SavePlaylistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SavePlaylistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserIngestionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserIngestionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblIngestion> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblIngestion>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserChannelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserChannelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblPlayoutPort> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblPlayoutPort>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Framework.LINQEntityBase Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Framework.LINQEntityBase)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class data_setCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public data_setCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Data.DataTable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PushVodIngestion.ServiceReference1.IService1>, PushVodIngestion.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;
        
        private EndOperationDelegate onEndGetDataUsingDataContractDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEntitiesDelegate;
        
        private EndOperationDelegate onEndGetEntitiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetEntitiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetEntitiesBasedOnConditionDelegate;
        
        private EndOperationDelegate onEndGetEntitiesBasedOnConditionDelegate;
        
        private System.Threading.SendOrPostCallback onGetEntitiesBasedOnConditionCompletedDelegate;
        
        private BeginOperationDelegate onBeginSavePlaylistDelegate;
        
        private EndOperationDelegate onEndSavePlaylistDelegate;
        
        private System.Threading.SendOrPostCallback onSavePlaylistCompletedDelegate;
        
        private BeginOperationDelegate onBegindata_commandDelegate;
        
        private EndOperationDelegate onEnddata_commandDelegate;
        
        private System.Threading.SendOrPostCallback ondata_commandCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserIngestionDelegate;
        
        private EndOperationDelegate onEndGetUserIngestionDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserIngestionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserChannelsDelegate;
        
        private EndOperationDelegate onEndGetUserChannelsDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserChannelsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveDelegate;
        
        private EndOperationDelegate onEndSaveDelegate;
        
        private System.Threading.SendOrPostCallback onSaveCompletedDelegate;
        
        private BeginOperationDelegate onBegindata_setDelegate;
        
        private EndOperationDelegate onEnddata_setDelegate;
        
        private System.Threading.SendOrPostCallback ondata_setCompletedDelegate;
        
        private BeginOperationDelegate onBeginBulk_CopyDelegate;
        
        private EndOperationDelegate onEndBulk_CopyDelegate;
        
        private System.Threading.SendOrPostCallback onBulk_CopyCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;
        
        public event System.EventHandler<GetEntitiesCompletedEventArgs> GetEntitiesCompleted;
        
        public event System.EventHandler<GetEntitiesBasedOnConditionCompletedEventArgs> GetEntitiesBasedOnConditionCompleted;
        
        public event System.EventHandler<SavePlaylistCompletedEventArgs> SavePlaylistCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> data_commandCompleted;
        
        public event System.EventHandler<GetUserIngestionCompletedEventArgs> GetUserIngestionCompleted;
        
        public event System.EventHandler<GetUserChannelsCompletedEventArgs> GetUserChannelsCompleted;
        
        public event System.EventHandler<SaveCompletedEventArgs> SaveCompleted;
        
        public event System.EventHandler<data_setCompletedEventArgs> data_setCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> Bulk_CopyCompleted;
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int value = ((int)(inValues[0]));
            return this.BeginGetData(value, callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            string retVal = this.EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync(int value) {
            this.GetDataAsync(value, null);
        }
        
        public void GetDataAsync(int value, object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        public PushVodIngestion.ServiceReference1.CompositeType GetDataUsingDataContract(PushVodIngestion.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDataUsingDataContract(PushVodIngestion.ServiceReference1.CompositeType composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PushVodIngestion.ServiceReference1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result) {
            return base.Channel.EndGetDataUsingDataContract(result);
        }
        
        private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PushVodIngestion.ServiceReference1.CompositeType composite = ((PushVodIngestion.ServiceReference1.CompositeType)(inValues[0]));
            return this.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result) {
            PushVodIngestion.ServiceReference1.CompositeType retVal = this.EndGetDataUsingDataContract(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataUsingDataContractCompleted(object state) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataUsingDataContractAsync(PushVodIngestion.ServiceReference1.CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        public void GetDataUsingDataContractAsync(PushVodIngestion.ServiceReference1.CompositeType composite, object userState) {
            if ((this.onBeginGetDataUsingDataContractDelegate == null)) {
                this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
            }
            if ((this.onEndGetDataUsingDataContractDelegate == null)) {
                this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
            }
            if ((this.onGetDataUsingDataContractCompletedDelegate == null)) {
                this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                        composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> GetEntities(string entityTypeName) {
            return base.Channel.GetEntities(entityTypeName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetEntities(string entityTypeName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEntities(entityTypeName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> EndGetEntities(System.IAsyncResult result) {
            return base.Channel.EndGetEntities(result);
        }
        
        private System.IAsyncResult OnBeginGetEntities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string entityTypeName = ((string)(inValues[0]));
            return this.BeginGetEntities(entityTypeName, callback, asyncState);
        }
        
        private object[] OnEndGetEntities(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> retVal = this.EndGetEntities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEntitiesCompleted(object state) {
            if ((this.GetEntitiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEntitiesCompleted(this, new GetEntitiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEntitiesAsync(string entityTypeName) {
            this.GetEntitiesAsync(entityTypeName, null);
        }
        
        public void GetEntitiesAsync(string entityTypeName, object userState) {
            if ((this.onBeginGetEntitiesDelegate == null)) {
                this.onBeginGetEntitiesDelegate = new BeginOperationDelegate(this.OnBeginGetEntities);
            }
            if ((this.onEndGetEntitiesDelegate == null)) {
                this.onEndGetEntitiesDelegate = new EndOperationDelegate(this.OnEndGetEntities);
            }
            if ((this.onGetEntitiesCompletedDelegate == null)) {
                this.onGetEntitiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEntitiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetEntitiesDelegate, new object[] {
                        entityTypeName}, this.onEndGetEntitiesDelegate, this.onGetEntitiesCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> GetEntitiesBasedOnCondition(string entityTypeName, string predicate, System.Collections.ObjectModel.ObservableCollection<object> value) {
            return base.Channel.GetEntitiesBasedOnCondition(entityTypeName, predicate, value);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetEntitiesBasedOnCondition(string entityTypeName, string predicate, System.Collections.ObjectModel.ObservableCollection<object> value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEntitiesBasedOnCondition(entityTypeName, predicate, value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> EndGetEntitiesBasedOnCondition(System.IAsyncResult result) {
            return base.Channel.EndGetEntitiesBasedOnCondition(result);
        }
        
        private System.IAsyncResult OnBeginGetEntitiesBasedOnCondition(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string entityTypeName = ((string)(inValues[0]));
            string predicate = ((string)(inValues[1]));
            System.Collections.ObjectModel.ObservableCollection<object> value = ((System.Collections.ObjectModel.ObservableCollection<object>)(inValues[2]));
            return this.BeginGetEntitiesBasedOnCondition(entityTypeName, predicate, value, callback, asyncState);
        }
        
        private object[] OnEndGetEntitiesBasedOnCondition(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Framework.LINQEntityBase> retVal = this.EndGetEntitiesBasedOnCondition(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEntitiesBasedOnConditionCompleted(object state) {
            if ((this.GetEntitiesBasedOnConditionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEntitiesBasedOnConditionCompleted(this, new GetEntitiesBasedOnConditionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEntitiesBasedOnConditionAsync(string entityTypeName, string predicate, System.Collections.ObjectModel.ObservableCollection<object> value) {
            this.GetEntitiesBasedOnConditionAsync(entityTypeName, predicate, value, null);
        }
        
        public void GetEntitiesBasedOnConditionAsync(string entityTypeName, string predicate, System.Collections.ObjectModel.ObservableCollection<object> value, object userState) {
            if ((this.onBeginGetEntitiesBasedOnConditionDelegate == null)) {
                this.onBeginGetEntitiesBasedOnConditionDelegate = new BeginOperationDelegate(this.OnBeginGetEntitiesBasedOnCondition);
            }
            if ((this.onEndGetEntitiesBasedOnConditionDelegate == null)) {
                this.onEndGetEntitiesBasedOnConditionDelegate = new EndOperationDelegate(this.OnEndGetEntitiesBasedOnCondition);
            }
            if ((this.onGetEntitiesBasedOnConditionCompletedDelegate == null)) {
                this.onGetEntitiesBasedOnConditionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEntitiesBasedOnConditionCompleted);
            }
            base.InvokeAsync(this.onBeginGetEntitiesBasedOnConditionDelegate, new object[] {
                        entityTypeName,
                        predicate,
                        value}, this.onEndGetEntitiesBasedOnConditionDelegate, this.onGetEntitiesBasedOnConditionCompletedDelegate, userState);
        }
        
        public bool SavePlaylist(PushVodIngestion.DataProvider.tblPlaylist playList) {
            return base.Channel.SavePlaylist(playList);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSavePlaylist(PushVodIngestion.DataProvider.tblPlaylist playList, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSavePlaylist(playList, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndSavePlaylist(System.IAsyncResult result) {
            return base.Channel.EndSavePlaylist(result);
        }
        
        private System.IAsyncResult OnBeginSavePlaylist(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PushVodIngestion.DataProvider.tblPlaylist playList = ((PushVodIngestion.DataProvider.tblPlaylist)(inValues[0]));
            return this.BeginSavePlaylist(playList, callback, asyncState);
        }
        
        private object[] OnEndSavePlaylist(System.IAsyncResult result) {
            bool retVal = this.EndSavePlaylist(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSavePlaylistCompleted(object state) {
            if ((this.SavePlaylistCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SavePlaylistCompleted(this, new SavePlaylistCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SavePlaylistAsync(PushVodIngestion.DataProvider.tblPlaylist playList) {
            this.SavePlaylistAsync(playList, null);
        }
        
        public void SavePlaylistAsync(PushVodIngestion.DataProvider.tblPlaylist playList, object userState) {
            if ((this.onBeginSavePlaylistDelegate == null)) {
                this.onBeginSavePlaylistDelegate = new BeginOperationDelegate(this.OnBeginSavePlaylist);
            }
            if ((this.onEndSavePlaylistDelegate == null)) {
                this.onEndSavePlaylistDelegate = new EndOperationDelegate(this.OnEndSavePlaylist);
            }
            if ((this.onSavePlaylistCompletedDelegate == null)) {
                this.onSavePlaylistCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSavePlaylistCompleted);
            }
            base.InvokeAsync(this.onBeginSavePlaylistDelegate, new object[] {
                        playList}, this.onEndSavePlaylistDelegate, this.onSavePlaylistCompletedDelegate, userState);
        }
        
        public void data_command(string sqlCommand) {
            base.Channel.data_command(sqlCommand);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begindata_command(string sqlCommand, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begindata_command(sqlCommand, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void Enddata_command(System.IAsyncResult result) {
            base.Channel.Enddata_command(result);
        }
        
        private System.IAsyncResult OnBegindata_command(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sqlCommand = ((string)(inValues[0]));
            return this.Begindata_command(sqlCommand, callback, asyncState);
        }
        
        private object[] OnEnddata_command(System.IAsyncResult result) {
            this.Enddata_command(result);
            return null;
        }
        
        private void Ondata_commandCompleted(object state) {
            if ((this.data_commandCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.data_commandCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void data_commandAsync(string sqlCommand) {
            this.data_commandAsync(sqlCommand, null);
        }
        
        public void data_commandAsync(string sqlCommand, object userState) {
            if ((this.onBegindata_commandDelegate == null)) {
                this.onBegindata_commandDelegate = new BeginOperationDelegate(this.OnBegindata_command);
            }
            if ((this.onEnddata_commandDelegate == null)) {
                this.onEnddata_commandDelegate = new EndOperationDelegate(this.OnEnddata_command);
            }
            if ((this.ondata_commandCompletedDelegate == null)) {
                this.ondata_commandCompletedDelegate = new System.Threading.SendOrPostCallback(this.Ondata_commandCompleted);
            }
            base.InvokeAsync(this.onBegindata_commandDelegate, new object[] {
                        sqlCommand}, this.onEnddata_commandDelegate, this.ondata_commandCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblIngestion> GetUserIngestion(long userSID) {
            return base.Channel.GetUserIngestion(userSID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUserIngestion(long userSID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserIngestion(userSID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblIngestion> EndGetUserIngestion(System.IAsyncResult result) {
            return base.Channel.EndGetUserIngestion(result);
        }
        
        private System.IAsyncResult OnBeginGetUserIngestion(object[] inValues, System.AsyncCallback callback, object asyncState) {
            long userSID = ((long)(inValues[0]));
            return this.BeginGetUserIngestion(userSID, callback, asyncState);
        }
        
        private object[] OnEndGetUserIngestion(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblIngestion> retVal = this.EndGetUserIngestion(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserIngestionCompleted(object state) {
            if ((this.GetUserIngestionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserIngestionCompleted(this, new GetUserIngestionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserIngestionAsync(long userSID) {
            this.GetUserIngestionAsync(userSID, null);
        }
        
        public void GetUserIngestionAsync(long userSID, object userState) {
            if ((this.onBeginGetUserIngestionDelegate == null)) {
                this.onBeginGetUserIngestionDelegate = new BeginOperationDelegate(this.OnBeginGetUserIngestion);
            }
            if ((this.onEndGetUserIngestionDelegate == null)) {
                this.onEndGetUserIngestionDelegate = new EndOperationDelegate(this.OnEndGetUserIngestion);
            }
            if ((this.onGetUserIngestionCompletedDelegate == null)) {
                this.onGetUserIngestionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserIngestionCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserIngestionDelegate, new object[] {
                        userSID}, this.onEndGetUserIngestionDelegate, this.onGetUserIngestionCompletedDelegate, userState);
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblPlayoutPort> GetUserChannels(long userSID) {
            return base.Channel.GetUserChannels(userSID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetUserChannels(long userSID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserChannels(userSID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblPlayoutPort> EndGetUserChannels(System.IAsyncResult result) {
            return base.Channel.EndGetUserChannels(result);
        }
        
        private System.IAsyncResult OnBeginGetUserChannels(object[] inValues, System.AsyncCallback callback, object asyncState) {
            long userSID = ((long)(inValues[0]));
            return this.BeginGetUserChannels(userSID, callback, asyncState);
        }
        
        private object[] OnEndGetUserChannels(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PushVodIngestion.DataProvider.tblPlayoutPort> retVal = this.EndGetUserChannels(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserChannelsCompleted(object state) {
            if ((this.GetUserChannelsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserChannelsCompleted(this, new GetUserChannelsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserChannelsAsync(long userSID) {
            this.GetUserChannelsAsync(userSID, null);
        }
        
        public void GetUserChannelsAsync(long userSID, object userState) {
            if ((this.onBeginGetUserChannelsDelegate == null)) {
                this.onBeginGetUserChannelsDelegate = new BeginOperationDelegate(this.OnBeginGetUserChannels);
            }
            if ((this.onEndGetUserChannelsDelegate == null)) {
                this.onEndGetUserChannelsDelegate = new EndOperationDelegate(this.OnEndGetUserChannels);
            }
            if ((this.onGetUserChannelsCompletedDelegate == null)) {
                this.onGetUserChannelsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserChannelsCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserChannelsDelegate, new object[] {
                        userSID}, this.onEndGetUserChannelsDelegate, this.onGetUserChannelsCompletedDelegate, userState);
        }
        
        public Framework.LINQEntityBase Save(Framework.LINQEntityBase entity, FrameWork.EntityState entityState) {
            return base.Channel.Save(entity, entityState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSave(Framework.LINQEntityBase entity, FrameWork.EntityState entityState, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSave(entity, entityState, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Framework.LINQEntityBase EndSave(System.IAsyncResult result) {
            return base.Channel.EndSave(result);
        }
        
        private System.IAsyncResult OnBeginSave(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Framework.LINQEntityBase entity = ((Framework.LINQEntityBase)(inValues[0]));
            FrameWork.EntityState entityState = ((FrameWork.EntityState)(inValues[1]));
            return this.BeginSave(entity, entityState, callback, asyncState);
        }
        
        private object[] OnEndSave(System.IAsyncResult result) {
            Framework.LINQEntityBase retVal = this.EndSave(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveCompleted(object state) {
            if ((this.SaveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveCompleted(this, new SaveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveAsync(Framework.LINQEntityBase entity, FrameWork.EntityState entityState) {
            this.SaveAsync(entity, entityState, null);
        }
        
        public void SaveAsync(Framework.LINQEntityBase entity, FrameWork.EntityState entityState, object userState) {
            if ((this.onBeginSaveDelegate == null)) {
                this.onBeginSaveDelegate = new BeginOperationDelegate(this.OnBeginSave);
            }
            if ((this.onEndSaveDelegate == null)) {
                this.onEndSaveDelegate = new EndOperationDelegate(this.OnEndSave);
            }
            if ((this.onSaveCompletedDelegate == null)) {
                this.onSaveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveCompleted);
            }
            base.InvokeAsync(this.onBeginSaveDelegate, new object[] {
                        entity,
                        entityState}, this.onEndSaveDelegate, this.onSaveCompletedDelegate, userState);
        }
        
        public System.Data.DataTable data_set(string sqlCommand) {
            return base.Channel.data_set(sqlCommand);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begindata_set(string sqlCommand, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begindata_set(sqlCommand, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Data.DataTable Enddata_set(System.IAsyncResult result) {
            return base.Channel.Enddata_set(result);
        }
        
        private System.IAsyncResult OnBegindata_set(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sqlCommand = ((string)(inValues[0]));
            return this.Begindata_set(sqlCommand, callback, asyncState);
        }
        
        private object[] OnEnddata_set(System.IAsyncResult result) {
            System.Data.DataTable retVal = this.Enddata_set(result);
            return new object[] {
                    retVal};
        }
        
        private void Ondata_setCompleted(object state) {
            if ((this.data_setCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.data_setCompleted(this, new data_setCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void data_setAsync(string sqlCommand) {
            this.data_setAsync(sqlCommand, null);
        }
        
        public void data_setAsync(string sqlCommand, object userState) {
            if ((this.onBegindata_setDelegate == null)) {
                this.onBegindata_setDelegate = new BeginOperationDelegate(this.OnBegindata_set);
            }
            if ((this.onEnddata_setDelegate == null)) {
                this.onEnddata_setDelegate = new EndOperationDelegate(this.OnEnddata_set);
            }
            if ((this.ondata_setCompletedDelegate == null)) {
                this.ondata_setCompletedDelegate = new System.Threading.SendOrPostCallback(this.Ondata_setCompleted);
            }
            base.InvokeAsync(this.onBegindata_setDelegate, new object[] {
                        sqlCommand}, this.onEnddata_setDelegate, this.ondata_setCompletedDelegate, userState);
        }
        
        public void Bulk_Copy(System.Data.DataTable dt, string destinationTable) {
            base.Channel.Bulk_Copy(dt, destinationTable);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginBulk_Copy(System.Data.DataTable dt, string destinationTable, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBulk_Copy(dt, destinationTable, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndBulk_Copy(System.IAsyncResult result) {
            base.Channel.EndBulk_Copy(result);
        }
        
        private System.IAsyncResult OnBeginBulk_Copy(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Data.DataTable dt = ((System.Data.DataTable)(inValues[0]));
            string destinationTable = ((string)(inValues[1]));
            return this.BeginBulk_Copy(dt, destinationTable, callback, asyncState);
        }
        
        private object[] OnEndBulk_Copy(System.IAsyncResult result) {
            this.EndBulk_Copy(result);
            return null;
        }
        
        private void OnBulk_CopyCompleted(object state) {
            if ((this.Bulk_CopyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Bulk_CopyCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Bulk_CopyAsync(System.Data.DataTable dt, string destinationTable) {
            this.Bulk_CopyAsync(dt, destinationTable, null);
        }
        
        public void Bulk_CopyAsync(System.Data.DataTable dt, string destinationTable, object userState) {
            if ((this.onBeginBulk_CopyDelegate == null)) {
                this.onBeginBulk_CopyDelegate = new BeginOperationDelegate(this.OnBeginBulk_Copy);
            }
            if ((this.onEndBulk_CopyDelegate == null)) {
                this.onEndBulk_CopyDelegate = new EndOperationDelegate(this.OnEndBulk_Copy);
            }
            if ((this.onBulk_CopyCompletedDelegate == null)) {
                this.onBulk_CopyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBulk_CopyCompleted);
            }
            base.InvokeAsync(this.onBeginBulk_CopyDelegate, new object[] {
                        dt,
                        destinationTable}, this.onEndBulk_CopyDelegate, this.onBulk_CopyCompletedDelegate, userState);
        }
    }
}
